# -*- coding: utf-8 -*-
"""Word Guess Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IQ0bD020Kn-f6vgUbUqh44WVz3Ti7ppN
"""

import random

store_g_l=[]
try_p=6
a=input("Enter a Name : ")
print("Enter to the game world",a)
print("ATTEMPT REMAINING : 6 ")

words=['apple','tree','goat','google','oracle','panda','orrange','dog','tank','ship','honda','itachi']

# Choose random word from list
guessed_word=random.choice(words)
guessed_word

hint = guessed_word[0]+guessed_word[-1]
hint

for guess in range(try_p):
  while True:
    letter = input('Guess the letter ')

    if len(letter) == 1:
      break
    else:
      print("Oops! Please guess a letter!")

  if letter in guessed_word:
    print('Yes!')
    store_g_l.append(letter)
  else:
    print('No!')

  if guess == 3:
    print()
    clue_request = input('Would you like a clue?')
    if clue_request.lower().startswith('y'):
      print()
      print('CLUE : The first and last letter of word is: ',hint)
    else:
      print('You\'re very confident!')

  
print()
print('''Noe Let's see what have you guessed soo far. You have guessed:''',len(store_g_l), 'letters correctly.')
print("These letters are : ",store_g_l)

word_guess = input('Guess the world word :')
if word_guess.lower() == guessed_word:
  print('Congrats! you are correct')
else:
  print('Sorry! The answer was,', guessed_word)

print()
input('Please press Enter to leave the program')